- README.md
- src/omero_cli_zarr.py
- src/raw_pixels.py
Ported the script from https://github.com/ome/omero-ms-zarr/blob/master/src/scripts/omero_to_zarr.py and updated with omero metadata
To test:
```
$ omero zarr Image:1 --output test
...
Created test/1.zarr
```
Also test the other arguments mentioned in the README (```--output``` and ```--cache_numpy```).
Use napari and the https://github.com/ome/ome-zarr-py to open in napari:
```
$ napari test/1.zarr
```
To export with bioformats2raw, use the ```--bf``` flag.
> Download via rawpixelsstore

- src/masks.py
- src/omero_cli_zarr.py
Work in progress (need to move Image export to a new sub command etc)
First implementation of exporting OMERO Masks as zarr file:
To test this branch:
```
$ omero zarr masks Image:6001240
Previous session expired for public on idr.openmicroscopy.org:4064
Server: [idr.openmicroscopy.org:4064]
Username: [public]
Password:
Created 6001240_masks.zarr
```
Then:
```
$ napari 6001240_masks.zarr
```
cc @joshmoore @manics
> Export masks as 4D zarr

- README.md
- src/omero_zarr/cli.py
- src/omero_zarr/masks.py
Effectively implements https://github.com/ome/omero-cli-zarr/pull/4 but with a hard-coded `0` for the mask name.
Main changes:
- Mask is stored under `IMAGEID.zarr/masks/0` instead of `IMAGEID_masks.zarr/0` (note the image data is optional, it is fine to have a mask without an image)
- Mask arrays are always 5D `(T, C, Z, Y, X)`
- Some mask dimensions may have size 1 instead of being the same size as the image. This indicates they should be expanded. E.g. If image `sizeC=3` but mask `sizeC=1` then the client should duplicate the mask for each `imageC`
- Adds some basic metadata to `IMAGEID.zarr/masks/0/.zattrs`, in particular `image.name` is the name of the image in the same Zarr. If the image is not included this is a URL to the remote image data.
- When creating a label image masks are …
> Change masks.py to put mask in a group under the image

- setup.py
I suspect this previously worked because the package was installed in editable mode.
Testing: `omero zarr ...` should work after `pip install .` (no `-e`) in a clean environment
> Add missing omero_zarr package

- src/omero_zarr/cli.py
- src/omero_zarr/masks.py
Follow on from https://github.com/ome/omero-cli-zarr/pull/8#discussion_r446173666 that introduces a third option for storage of masks called, 6d, which can be chosen along with the other options:
* `--style=labelled` for the single 5D labelled image
* `--style=split` for several 5D images, named after the ROI
Converting the 6D array back into a labelled image can be done with:
```
s = zarr.open("path/to/6d/array")
shape = list(s.shape)[1:]
chunks = list(s.chunks)[1:]
a = zarr.zeros(shape, chunks=chunks, dtype='i8')
a = np.zeros(shape, dtype='i8')
for x in range(s.shape[0]):
a[s[x]] = x + 1
viewer.add_labels(a, name="masks")
Out[8]: <Labels layer 'masks' at 0x7fb209b0b320>
```
Testing with:
```
rm -rf 6001240.zarr/{masks,6d,labelled,split};for x in "6d" "labelled" "split"; do time omero …
```
> Introduce 6D mask storage

- src/omero_zarr/cli.py
- src/omero_zarr/masks.py
Follow-on from #9. Allows splitting overlapping labelled images into separate arrays under `masks/`.
```
omero zarr export Image:5514375
omero hql --style=plain "select distinct s.textValue, s.roi.id from Shape s where s.roi.image.id = 5514375" --limit=-1 | tee 5514375.rois
omero zarr masks Image:5514375 --mask-map=5514375.rois
```
```
#!/usr/bin/env python
import napari
import zarr
imagename = "5514375.zarr"
masks = zarr.open(f"{imagename}/masks")
with napari.gui_qt():
viewer = napari.Viewer()
viewer.open(f"{imagename}")
def to_rgba(v):
return [int(x) for x in v.to_bytes(4, signed=True, byteorder='big')]
for name in ("Cell", "Chromosomes"):
mask = masks[name]
colors = mask.attrs["color"]
colors = {int(k):to_rgba(v) for (k, v) in colors.items()}
viewer.add_labels(mask, name=name, …
```
> Add mask-map logic

- README.md
Add instructions from #9 and #11.
I realise that these arguments are described in the cli help, but I find them easier to find and understand when you can read them on the page.
Also includes hql for creating mask-map.
> Add mask export args to README

- src/omero_zarr/cli.py
- Use `image.getImportedImageFilePaths()` to get the file paths to the image. This should solve https://github.com/ome/omero-cli-zarr/issues/15 ?
- When using `--bf` it is now expected that the bioformats2raw binary is in the `$PATH`; no setting of environment variable necessary any longer.
- Get the path to the managed repo from the `client`; again remove the necessasity of an environment variable.
- The various bioformats2raw options are now only part of the 'export' subcommand.
**Test:** Add the `bioformats2raw/bin` directory to the `$PATH` and run something like `omero zarr export --bf Image:123` Would be good to test with "normal" and "inplace imported" image.
> Improve bioformats2raw export

- .github/workflows/precommit.yml
- .gitignore
- .isort.cfg
- .pre-commit-config.yaml
- README.md
- src/omero/plugins/zarr.py
- src/omero_zarr/cli.py
- src/omero_zarr/masks.py
- src/omero_zarr/raw_pixels.py
- Use `ome_zarr.scale` to generate multiscale labels
- Improve link to source image metadata
- Drop support for 6D
- Fix README for `--output` (fix #26)
> Multiscale support

- .bumpversion.cfg
- .isort.cfg
- src/omero_zarr/cli.py
- src/omero_zarr/raw_pixels.py
On top of #28.
Adds multiresolutions for each Image, scaling each 2D plane down by a factor of 2, until smaller than 96 on longest side.
NB: this doesn't use ome-zarr-py to do the scaling (but uses the same underlying cv2 method) because we're scaling a 2D plane each time, not 5D.
cc @sbesson, @dominikl, @joshmoore 
TODO:
- Add arguments to allow you to turn this on/off and to choose target size (and to choose scaling method?)
> Plate multiscales

- src/omero_zarr/raw_pixels.py
Add acquisition, row and column names to the metadata. 
Example:
```
> cat 51.zarr/.zattrs 
{
"plate": {
"col_names": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12
],
"columns": 12,
"plateAcquisitions": {
"path": "Run 51"
},
"row_names": [
"F",
"E",
"H",
"A",
"G",
"B",
"D",
"C"
],
"rows": 8
}
}
```
Shall I rather 'break' the previous code and use `rows` instead of `row_names`? 
Addresses https://github.com/ome/omero-cli-zarr/issues/31 .
/cc @will-moore
> Row column names

- .github/workflows/publish_pypi.yml
Also uses a generic check on `repository_owner` to prevent failures on forks
> Fix conditional statement to skip PyPI publication for forks rather than tags

- .github/workflows/publish_pypi.yml
Originally motivated by https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi,
the continuous delivery to test PyPI failed for two separate reasons:
- distributions with the same version cannot be overwritten
- dev version generated by setuptools_scm are generally PEP440 incompatible
Partly reverts #37, see also the discussion https://github.com/ome/omero-cli-zarr/pull/33. This PR preserves the PyPI publication workflow on tags (and runs the packaging command for every push so that we would spot broken builds)
> Remove publication to test PyPI

- src/omero_zarr/raw_pixels.py
See https://github.com/ome/omero-ms-zarr/issues/76#issuecomment-721068552
`omero zarr export Plate:1` now exports 'well' metadata like
```
"well": {
"images": [
{"path": "0"},
{"path": "1"}
]
}
```
and 'plate' metadata like:
```
"plate": {
"columns": [
{"name": "1"}, {"name": "2"}, {"name": "3"}
],
"rows": [
{"name": "A"}, {"name": "B"}
],
"wells": [
{"path": "0/A/3"},
{"path": "0/B/2"},
{"path": "0/A/1"},
{"path": "0/B/3"},
{"path": "0/A/2"},
{"path": "0/B/1"}
],
"field_count": 1,
"name": "plate1_1_013",
"acquisitions": [
{"path": "0"}
],
}
```
> Well metadata

- src/omero_zarr/cli.py
- src/omero_zarr/masks.py
- src/omero_zarr/raw_pixels.py
- src/omero_zarr/util.py
Adds the functionality for exporting masks/labels for plates.
It exports the masks in a path structure like this:
```
13855.zarr:
...
0/A/1/Field_1/0/0.0.0.0.0
0/A/1/Field_1/0/0.1.0.0.0
...
0/A/1/Field_1/labels/0/0/0.0.0.0.0
0/A/1/Field_1/labels/0/0/0.0.0.0.1
...
```
For testing I used plate `plate1_1_013` on merge-ci (user-3), doesn't take too long to export (about 10-15 min the first time).
```
omero zarr --cache_numpy export Plate:13855
omero zarr masks Plate:13855
```
Or create your own masks with a simple segmentation. I pasted a script together (based on idr0079 maks import script): https://gist.github.com/dominikl/0c65cc18d57b51c509e93e53c1c44bc6 .
Waiting for #43 to merged, will rebase then.
> Export plate masks

- src/omero_zarr/raw_pixels.py
While working on https://github.com/ome/ngff/pull/5 and creating representative plates using `omero-cli-zarr 0.0.7`, I realized that an `acquisitions` key is always created in the plate metadata even if no plate acquisitions are defined. At the well-metadata, `acquisition` is skipped if the field of view is not associated with an acquisition.
This unifies the behavior by making `acquisitions` truly optional in the case there is a single plate acquisition with no associated metadata.
> Skip acquisitions key if no plate acquisition exists

- .isort.cfg
- src/omero_zarr/cli.py
- src/omero_zarr/masks.py
Support export of Polygons on an Image (or Plate) to labels.
To test, find an Image with Polygons e.g. on idr0001 image:
```
$ omero zarr export Image:1229801
$ omero zarr polygons Image:1229801
$ napari 1229801.zarr
```
> Add 'polygons' command like 'masks'

- .bumpversion.cfg
- .isort.cfg
- setup.py
- src/omero_zarr/cli.py
- src/omero_zarr/masks.py
- src/omero_zarr/raw_pixels.py
Adds `properties` to labels `.zattrs` exported from OMERO.
See functionality tests below. But first question is probably what we want to name these properties and if we want them included by default or only with a cli argument?
```
"properties": [
{
"label-value": 1,
"omero:roiId": 212825,
"omero:shapeId": 390575
},
```
To Test - need an Image or Plate with masks
- `omero zarr export Image or Plate`
- `omero zarr masks (same Image or Plate)`
- Open the `image/labels/0/.zattrs` in a text editor to see properties.
- And/or `napari path/to/image` with `ome-zarr-py` at https://github.com/ome/ome-zarr-py/pull/61 installed should display properties when you mouse-over a mask.
> label properties

- src/omero_zarr/raw_pixels.py
- `add_raw_image` allows a non-omero numpy array to be converted
- `add_group_metadata` can add the multiscales metadata without an OMERO image.
This is intended to support the creation of custom converters that can reuse these methods.
Example:
```py
import numpy as np
from zarr.hierarchy import open_group
from omero_zarr import raw_pixels
a = np.random.randint(0, 10, (8, 7, 6))
def planes():
for z in range(a.shape[2]):
yield a[:, :, z]
root = open_group('test876', mode="w")
c = raw_pixels.add_raw_image(
planes=planes(),
size_x=a.shape[1], size_y=a.shape[0], size_z=a.shape[2],
size_c=1, size_t=1,
level_count=2,
d_type=np.int8,
parent=root)
raw_pixels.add_group_metadata(root, None, c)
```
> Refactor add_image to be reusable outside OMERO

- .pre-commit-config.yaml
- src/omero_zarr/masks.py
- src/omero_zarr/raw_pixels.py
see: https://github.com/ome/ngff/pull/40
> Bump to 0.2: use nested chunks

- src/omero_zarr/__init__.py
- src/omero_zarr/raw_pixels.py
To test, try exporting 2D, 2D, 4D and 5D images.
```
$ omero zarr export Image:1
```
Z, C & T dimensions where size=1 should be ignored, and not included in the exported v0.3 OME_NGFF.
Also the `.zattrs` `multiscales` should list the used dimensions as `axes`, e.g: `"axes": ["t", "c", "y", "x"]`
> export v0.3 ome ngff

- src/omero_zarr/cli.py
The breaking changes of bioformat2raw 0.3.0 has broken `omero zarr export --bf`. These commits provide the minimal set of changes to restore the command functionality. This currently _only_ support bioformats2raw 0.3.0 and drops support for 0.2.x but see below for the discussion on the flag support:
Tested on `pilot-zarr1-dev` with `omero --debug DEBUG zarr export --bf Image:13422206`.
This initial work raises a few high-level questions on the future of this option. As a general rule, most of the support and testing has been added to the OMERO-only export workflow. This means most of the nice recent features do not apply to the `--bf` option like the rendering setting in the Zarr metadata, the HCS support... Additionally the layout of the OMERO export is different from the …
> Fix --bf option for bioformats2raw 0.3.0

- .pre-commit-config.yaml
- src/omero_zarr/cli.py
- src/omero_zarr/raw_pixels.py
Follow-up of #75, this PR:
- unifies the layout of the generated Zarr to comply with the format of `omero export Image:<id>`. The image series is passed to bioformats2raw and the unique image group (`<fileset>/0`) is renamed as `<id>.zarr`
- separates the multiscale metadata addition from the omero metadata addition in `raw_pixels`
- adds the omero and creator metadata to the Zarr generated by bioformats2raw
The `add_omero_metadata` and `add_toplevel_metadata` are arguably outside the scope of the `raw_pixels` module and could be moved elsewhere (`utils`? new module?)
> bioformats2raw export: unify Zarr layout and add OMERO metadata

- .isort.cfg
- src/omero_zarr/raw_pixels.py
Previously, the CLI plugin relied on the `opencv` dependency transitively through `ome-zarr-py`. However, this dependency has been dropped as part of the 0.3 specification support in https://github.com/ome/ome-zarr-py/pull/89. With the release of `ome-zarr-py==0.0.24`, @dominikl has established the  standard installation of `omero-cli-zarr` is currently broken (without a manual installation of the dependency):
```
(zarr) ➜  Downloads omero zarr --help
Error loading: /Users/dom/miniconda3/envs/zarr/lib/python3.9/site-packages/omero/plugins/zarr.py
Traceback (most recent call last):
File "/Users/dom/miniconda3/envs/zarr/lib/python3.9/site-packages/omero/cli.py", line 1690, in loadpath
execfile(str(pathobj), loc)
File "/Users/dom/miniconda3/envs/zarr/lib/python3.9/site-packages/past/builtins/ …
```
> Remove opencv dependency

- setup.py
- src/omero_zarr/cli.py
Addresses some usability feedback reported @pwalczysko and @dominikl. The `--output` argument is currently defined at the level of the `zarr` command parser making it hard to discover via the command help or remember.
4a04e23 proposes to specify the argument explicitly for each command. From the usage perspective, this means
```
omero zarr export --help
```
should also list the `--output OUTPUT`  argument. In terms of functional testing, the following command should work
```
omero zarr export Image:1 --output /tmp 
```
The previous behavior is conserved so that existing usage does not break i.e. 
```
omero zarr --output /tmp export Image:1
```
In the unlikely case where `--output` is specified twice, local testing suggests the last specified option takes precedence
> Also define --output option at the subcommand parser for usability

- setup.py
- src/omero_zarr/masks.py
- src/omero_zarr/raw_pixels.py
- src/omero_zarr/util.py
As discussed in https://github.com/ome/omero-cli-zarr/pull/93#discussion_r790864982 the API for `write_multiscales_metadata()` has changed in ome/ome-zarr-py#162 and this PR uses that new API.
Also, this now exports `scales` metadata as a list `[1, 1, 0.5, 0.3, 0.3]` instead of using `axesIndices`.
> Scale dict

- src/omero_zarr/cli.py
Currently, `--bf` requires access to the managed repository.
If, however, a copy of the necessary files are already available
locally, it would be necessary to first determine where they live
on the server, and place the files in exactly that location.
The `--bfpath` option takes the absolute or relative path to the
files and uses that rather than inspect the OMERO repository.
> Add --bfpath option

- src/omero_zarr/masks.py
Fixes #115
This PR
- Uses the ROI ID, subtracting the smallest ROI ID, as the mask value
- Uses the smallest `np.dtype` that is required for the maximum mask value.
To test: export labels and check dtype (was previously `"<i8"`):
```
$ omero zarr export Image:6001240
$ omero zarr masks Image:6001240
$ cat 6001240.zarr/labels/0/0/.zarray | grep dtype
"dtype": "<i2",
```
Napari should still show masks correctly, with omero IDs shown when mousing over shapes:
```$ napari --plugin napari-ome-zarr 6001240.zarr```
Mousing over label at bottom-left:
Check shape ID:
https://idr.openmicroscopy.org/iviewer/?shape=1664664
> Choose smallest np.dtype that handles labels data

- setup.py
- src/omero_zarr/masks.py
Testing `write_multiscale_labels()` added in https://github.com/ome/ome-zarr-py/pull/178/
> Use of write_multiscale_labels for image

- README.rst
- src/omero_zarr/cli.py
- src/omero_zarr/masks.py
Add support for `--overlaps=dtype_max` to cli for Image and Plate export of polygons and masks. Also update README with this (and mention export of polygons).
To test, using IDR: (idr0001):
```
$ omero zarr export Image:1229801
$ omero zarr polygons Image:1229801 --overlaps=dtype_max
$ napari --plugin napari-ome-zarr 1229801.zarr
```
Not tested Plate export yet, or export of `masks`.
Overlapping regions should be exported with a value of `dtype.max`.
NB: The masks for the Image above are exported as a single plane with Z index of 0. Only by scrolling to first Z-index are they visible (See screenshot)
I wonder if we can use `coordinateTransformations` to solve this?
Without the `--overlaps` arg, we get:
```
File "/Users/wmoore/Desktop/ZARR/omero-cli-zarr/src/omero_zarr/masks.py", line 529, …
```
> add --allow_overlaps arg to cli

- CHANGELOG.md
- src/omero_zarr/util.py
See https://github.com/ome/ngff/pull/157
This is a corresponding fix to update all axes "units" to "unit" (as in the Spec).
> Fix units -> unit

- .isort.cfg
- .pre-commit-config.yaml
- README.rst
- src/omero_zarr/cli.py
- src/omero_zarr/raw_pixels.py
Fixes #111
This adds support for exporting big images in a tile-based approach instead of a plane-based approach.
As suggested by @joshmoore - this tile-based approach is used for ALL images (instead of using the whole plane for as a single chunk as before).
First we write a full-size array at `0`, a tile at a time.
Then resize via `ome_zarr.dask_utils.resize` (see bug-fix at https://github.com/ome/ome-zarr-py/pull/244)
to create a pyramid.
Other changes:
The `--numpy_cache` functionality has been replaced.
Previously, if you anticipated connection issues with OMERO, you could use the `--numpy_cache` option to cache chunks to disk at the same time as writing them to zarr. The problem with this was that if you lost connection and weren't expecting it, then you had nothing cached. Also, …
> Big images

- CHANGELOG.md
- src/omero_zarr/masks.py
As reported by @jburel, trying to export labels with recent numpy (e.g. `numpy==1.24.3`) fails (Error below).
See https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
<details><summary>Error</summary>
```
$ omero zarr masks Image:6001240
/Users/wmoore/Desktop/ZARR/omero-cli-zarr/src/omero_zarr/masks.py:54: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
1: np.bool,
Error loading: /Users/wmoore/Desktop/ZARR/omero-cli-zarr/src/omero/plugins/zarr.py
Traceback (most recent call last):
File "/Users/wmoore/opt/anaconda3/envs/omeroweb2/lib/python3.9/site-packages/omero/cli.py", line 1690, in loadpath
execfile(str(pathobj), loc)
File "/Users/wmoore/opt/anaconda3/envs/omeroweb2/lib/python3.9/site-packages/past/builtins/misc.py", line 154, in …
```
> Remove np.bool alias

- src/omero_zarr/raw_pixels.py
I noticed that a bug introduced in https://github.com/ome/omero-cli-zarr/pull/134
When creating pyramids with `downsample_pyramid_on_disk()` the `da.to_zarr()` doesn't respect dimension separator.
For example of data exported with this issue: see https://ome.github.io/ome-ngff-validator/?source=https://uk1s3.embassy.ebi.ac.uk/idr0036/zarr/4403.zarr/A/1/0/
Fix is similar to https://github.com/ome/ome-zarr-py/pull/243
To test:
```
$ omero zarr export Image:123
```
check that array at `123.zarr/1/` has dimension separator `/`
> Use correct dimension_separator when downsampling

- src/omero_zarr/raw_pixels.py
Fixes a bug introduced by https://github.com/ome/omero-cli-zarr/pull/144 where the `well/field/image` path wasn't being passed to `da.to_zarr()` when downsampling images during Plate export.
To test:
```
omero zarr export Plate:123
```
This bug didn't affect the export of single Images (which was tested on that PR).
Without this fix, the first downsampled image `1` gets written to `plate.zarr/1/.zarray` and then this is not found when we try to read it to downsample again (since we're still looking in the "right" place at `plate.zarr/A/1/0/1/.zarray`):
```
Traceback (most recent call last):
File "/Users/wmoore/opt/anaconda3/envs/omeroweb2/lib/python3.9/site-packages/zarr/core.py", line 243, in _load_metadata_nosync
meta_bytes = self._store[mkey]
File …
```
> Fix path/to/image when exporting Plate images

- src/omero_zarr/raw_pixels.py
Images in OMERO with `float` pixelType are `float-32` (`f4`: 4 bytes per pixel) but are currently exported as `f8`.
E.g. https://idr.openmicroscopy.org/webclient/?show=image-10648046 was exported as
https://ome.github.io/ome-ngff-validator/?source=https://uk1s3.embassy.ebi.ac.uk/bia-integrator-data/S-BIAD852/971f2809-c748-4259-8044-81ba6c774fdd/971f2809-c748-4259-8044-81ba6c774fdd.zarr
This is because we have previously used `np.dtype(omeroDtype)` which gives the `float64` dtype by default:
```
>>> from omero.model.enums import PixelsTypefloat
>>> PixelsTypefloat
'float'
>>> np.dtype(PixelsTypefloat)
dtype('float64')
```
To test:
```
omero zarr export Image:10648046
ome_zarr view 10648046.zarr
```
Should see `Type: <f4`
> Pixel type fix
